"""add assignments table

Revision ID: 957ae9266336
Revises: 533cd9a13786
Create Date: 2026-01-21 10:03:08.404444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '957ae9266336'
down_revision: Union[str, Sequence[str], None] = '533cd9a13786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_project_skill')
    )
    op.create_table('volunteer_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_skill_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_skill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='assignmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_skill_id'], ['project_skills.id'], ),
    sa.ForeignKeyConstraint(['volunteer_skill_id'], ['volunteer_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('volunteers_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers_skills',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('volunteers_skills_ibfk_1')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('volunteers_skills_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('assignments')
    op.drop_table('volunteer_skills')
    op.drop_table('project_skills')
    # ### end Alembic commands ###
